# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-21 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='deck_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pingtai_name', models.CharField(max_length=20, verbose_name='\u5e73\u53f0\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u5e73\u53f0',
                'verbose_name_plural': '\u5e73\u53f0',
            },
        ),
        migrations.CreateModel(
            name='field_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lingyu_name', models.CharField(max_length=20, verbose_name='\u9886\u57df\u540d\u79f0')),
                ('deck_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sucai.deck_type', verbose_name='\u5e73\u53f0')),
            ],
            options={
                'verbose_name': '\u9886\u57df',
                'verbose_name_plural': '\u9886\u57df',
            },
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='\u6807\u9898')),
                ('message_type', models.IntegerField(default=0, verbose_name='\u6d88\u606f\u7c7b\u578b')),
                ('pinglun_count', models.IntegerField(default=0, verbose_name='\u8bc4\u8bba\u91cf')),
                ('yuedu_count', models.IntegerField(default=0, verbose_name='\u9605\u8bfb\u91cf')),
                ('time', models.CharField(max_length=100, verbose_name='\u6d88\u606f\u65f6\u95f4')),
                ('author', models.CharField(max_length=100, verbose_name='\u4f5c\u8005')),
                ('author_img', models.CharField(max_length=300, verbose_name='\u4f5c\u8005\u5934\u50cf\u94fe\u63a5')),
                ('message_content', models.CharField(max_length=8000, verbose_name='\u6d88\u606f\u5185\u5bb9')),
                ('message_url', models.CharField(max_length=200, verbose_name='\u6587\u7ae0\u94fe\u63a5')),
                ('deck_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sucai.deck_type', verbose_name='\u5e73\u53f0')),
                ('field_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sucai.field_type', verbose_name='\u9886\u57df')),
            ],
            options={
                'verbose_name': '\u6d88\u606f',
                'verbose_name_plural': '\u6d88\u606f',
            },
        ),
        migrations.CreateModel(
            name='message_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_title', models.CharField(max_length=200, null=True, verbose_name='\u56fe\u7247\u6807\u9898')),
                ('services_img', models.ImageField(upload_to='img', verbose_name='\u6d88\u606f\u56fe\u7247')),
                ('services_img_two', models.ImageField(blank=True, upload_to='img', verbose_name='\u6d88\u606f\u56fe\u7247')),
                ('services_img_three', models.ImageField(blank=True, upload_to='img', verbose_name='\u6d88\u606f\u56fe\u7247')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sucai.message', verbose_name='\u6d88\u606f')),
            ],
            options={
                'verbose_name': '\u6d88\u606f\u56fe\u7247',
                'verbose_name_plural': '\u6d88\u606f\u56fe\u7247',
            },
        ),
    ]
