# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-22 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sucai', '0002_auto_20180522_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='deck_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sucai.deck_type', verbose_name='\u5e73\u53f0'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_content',
            field=models.CharField(blank=True, max_length=8000, null=True, verbose_name='\u6d88\u606f\u5185\u5bb9'),
        ),
    ]
