# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-22 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sucai', '0003_auto_20180522_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='author_img',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='\u4f5c\u8005\u5934\u50cf\u94fe\u63a5'),
        ),
        migrations.AlterField(
            model_name='message',
            name='field_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sucai.field_type', verbose_name='\u9886\u57df'),
        ),
    ]
